# 워크플로의 이름 지정
name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set artifact
        run: |
          echo "artifact=$(ls ./build/libs/*.jar | head -n 1)" >> $GITHUB_ENV

      - name: Debug artifact
        run:
          echo "Deploying artifact: ${{ env.artifact }}"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          ARTIFACT: ${{ env.artifact }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          mkdir -p ~/.ssh
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          
          ssh -i private_key.pem $USER@$HOST "mkdir -p /home/$USER/app && chmod 755 /home/$USER/app"
          
          scp -i private_key.pem $ARTIFACT $USER@$HOST:/home/$USER/app/
          
          ssh -i private_key.pem $USER@$HOST "java -jar /home/$USER/app/$(basename $ARTIFACT)"
