# 워크플로의 이름 지정
name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Set artifact
        run: |
          echo "artifact=$(ls ./build/libs/*.jar | head -n 1)" >> $GITHUB_ENV

      - name: Debug artifact
        run: |
          echo "Deploying artifact: ${{ env.artifact }}"

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
          ARTIFACT: ${{ env.artifact }}
        run: |
          # SSH 비공개 키를 파일로 저장
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # ~/.ssh 디렉토리 생성
          mkdir -p ~/.ssh

          # EC2 서버의 호스트 키를 known_hosts에 추가
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # EC2 서버에서 배포 디렉토리가 없으면 생성 (디렉토리 존재 여부 체크 후 생성)
          ssh -i private_key.pem $USER@$HOST "if [ ! -d /home/$USER/app ]; then mkdir -p /home/$USER/app; fi"

          # EC2 서버에 배포 파일 전송
          scp -i private_key.pem ./build/libs/$ARTIFACT $USER@$HOST:/home/$USER/app/

          # EC2 서버에서 애플리케이션 실행
          ssh -i private_key.pem $USER@$HOST "java -jar /home/$USER/app/$ARTIFACT"
